experiment_name: 'solubility_prediction_ESMFold_embedding'

num_epochs: 15
batch_size: 72
log_iterations: 100
patience: 4
optimizer_parameters:
  lr: 1.0e-3

target: sol
unknown_solubility: False

exp_name: biLSTM_TextCNN

optimizer: AdamW

# Paths to Data
train_embeddings: './data/validation_embeddings.h5'
val_embeddings: './data/validation_embeddings.h5'
test_embeddings: './data/validation_embeddings.h5'
train_remapping: './data/val_dataset.csv'
val_remapping: './data/val_dataset.csv'
test_remapping: './data/val_dataset.csv'

# Model parameters
model_type: 'biLSTM_TextCNN'
model_parameters:
  dropout: 0.2
  kernel_size: 9
  output_dim: 1
